[build]
  base = "."
  publish = "dist"  # Cambiar el directorio de implementación a "dist"
  command = "npm run build"  # Usar el comando "npm run build"

[context.production.environment]
  YARN_VERSION = "1.22.4"

[context.branch-deploy.environment]
  YARN_VERSION = "1.22.4"

[[redirects]]
  from = "*"
  to = "/index.html"
  status = 200
